---
version: "3"
services:
  wordpress:
    build: https://b02e5a0c7adff5406bd6e86e7b7349dd97a994ce@github.com/NUSOC/docker-wordpress.git
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /<shared_data_path>/wp-content/plugins:/var/www/wordpress/wp-content/plugins
      - /<shared_data_path>/wp-content/themes:/var/www/wordpress/wp-content/themes
      - /<shared_data_path>/wp-content/uploads:/var/www/wordpress/wp-content/uploads
      - /<shared_data_path>/wp-content/cache:/var/www/wordpress/wp-content/cache
      - /opt/backups:/var/www/wordpress/wp-content/ai1wm-backups
    environment:
      WORDPRESS_DB_HOST: nusoc-externalapp-db.caog5ril1laa.us-east-2.rds.amazonaws.com:3306
      WORDPRESS_DB_USER: $DBUSER
      WORDPRESS_DB_PASSWORD: $DBPASS
      WORDPRESS_DB_NAME: $DBNAME
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 0
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct' );
        define('DISALLOW_FILE_EDIT', true );
        define('WP_REDIS_HOST', 'socwp-redis.ajx38y.0001.use2.cache.amazonaws.com' );
        define('WP_REDIS_MAXTTL', 86400 );
        define('WP_REDIS_PREFIX', '$DBNAME' );
        define('WP_CACHE_KEY_SALT', '$DBNAME' );
        define('WPFC_MULTI_SITE_BETA', true );
        define('WP_ALLOW_MULTISITE', true );
        define('MULTISITE', true );
        define('SUBDOMAIN_INSTALL', false );
        define('DOMAIN_CURRENT_SITE', '$SITENAME' );
        define('PATH_CURRENT_SITE', '/' );
        define('SITE_ID_CURRENT_SITE', 1 );
        define('BLOG_ID_CURRENT_SITE', 1 );
        define('WP_DEBUG', false );
        define('WP_DEBUG_DISPLAY', false );
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: $SITENAME
